import type { Event, Spot } from "@/lib/types";

const now = new Date().toISOString();

export const demoEvents: Event[] = [
  {
    id: "evt_fujisawa",
    slug: "fujisawa",
    name: "藤沢産業フェスタ",
    publicTitle: "FUJISAWA ENERGY MISSION",
    status: "published",
    theme: {
      backgroundImageUrl: "/demo/fujisawa-bg.jpg",
      storyTitle: "未来都市ふじさわのエネルギーを修復せよ",
      storyBody:
        "あなたはエネルギー・エージェント。街に残された3つのエネルギースポットを修復しよう。",
      primaryColor: "#0ea5e9",
      accentColor: "#22c55e",
    },
    rally: {
      requiredSpotCount: 3,
      successEnergyPerSpot: 34,
      introEnabled: true,
      soundEnabled: false,
    },
    coupon: {
      enabled: true,
      title: "コンプリート特典",
      description: "受付で景品と交換できます。",
      prefix: "FJM",
      rewardType: "coupon",
      qrMode: "code",
      redeemNote: "スタッフにQRコードをご提示ください。",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "evt_housing_1",
    slug: "abc-housing-tsujido",
    name: "住宅展示場 春フェア",
    publicTitle: "HOUSING ENERGY MISSION",
    status: "published",
    theme: {
      backgroundImageUrl: "/demo/housing-bg.jpg",
      storyTitle: "モデルハウスを巡ってエネルギーを集めよう",
      storyBody:
        "会場内にあるチェックポイントを見つけて撮影し、ミッションをクリアしてください。",
      primaryColor: "#f97316",
      accentColor: "#eab308",
    },
    rally: {
      requiredSpotCount: 3,
      successEnergyPerSpot: 34,
      introEnabled: true,
      soundEnabled: false,
    },
    coupon: {
      enabled: true,
      title: "来場特典",
      description: "受付でノベルティ引換ができます。",
      prefix: "AHTS",
      rewardType: "gift",
      qrMode: "code",
      redeemNote: "景品交換所でスタッフにご提示ください。",
    },
    createdAt: now,
    updatedAt: now,
  },
];

export const demoSpots: Spot[] = [
  {
    id: "spot1",
    eventId: "evt_fujisawa",
    title: "スポット1",
    description: "見本と同じ場所を撮影しよう",
    order: 1,
    refImageUrl: "/demo/ref1.jpg",
    thumbnailUrl: "/demo/ref1.jpg",
    hintText: "広場の見え方に注目",
    energyGain: 34,
    active: true,
  },
  {
    id: "spot2",
    eventId: "evt_fujisawa",
    title: "スポット2",
    description: "別の角度でもOK",
    order: 2,
    refImageUrl: "/demo/ref2.jpg",
    thumbnailUrl: "/demo/ref2.jpg",
    hintText: "建物の形がヒント",
    energyGain: 33,
    active: true,
  },
  {
    id: "spot3",
    eventId: "evt_fujisawa",
    title: "スポット3",
    description: "最後のエネルギースポット",
    order: 3,
    refImageUrl: "/demo/ref3.jpg",
    thumbnailUrl: "/demo/ref3.jpg",
    hintText: "周囲の景色をよく見て",
    energyGain: 33,
    active: true,
  },
  {
    id: "house1",
    eventId: "evt_housing_1",
    title: "モデルハウスA",
    description: "同じ場所を撮影",
    order: 1,
    refImageUrl: "/demo/ref1.jpg",
    thumbnailUrl: "/demo/ref1.jpg",
    hintText: "玄関まわりがヒント",
    energyGain: 34,
    active: true,
  },
  {
    id: "house2",
    eventId: "evt_housing_1",
    title: "モデルハウスB",
    description: "特徴的な場所を見つけよう",
    order: 2,
    refImageUrl: "/demo/ref2.jpg",
    thumbnailUrl: "/demo/ref2.jpg",
    hintText: "窓や外壁の形に注目",
    energyGain: 33,
    active: true,
  },
  {
    id: "house3",
    eventId: "evt_housing_1",
    title: "モデルハウスC",
    description: "ラストミッション",
    order: 3,
    refImageUrl: "/demo/ref3.jpg",
    thumbnailUrl: "/demo/ref3.jpg",
    hintText: "外観の特徴を探そう",
    energyGain: 33,
    active: true,
  },
];